### ISSUE TITLE
Fails instantly with dependency error

### ISSUE THREAD

**Issue by b-gyula** [vert-x3/vertx-scala.g8#10]
### Version

Which version(s) did you encounter this bug ? [6156df7](https://github.com/vert-x3/vertx-scala.g8/commit/6156df7fd331043af631d77d0773972772dfb6ce)

### Context

I tried to build it from scratch, but fails instantly with dependency error

### Steps to reproduce

1. type: `sbt new vert-x3/vertx-scala.g8`
2. type: `cd vertx-scala`
3. type: `sbt reStart`

*ERROR:*
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading io.vertx:vertx-lang-scala3:4.4.6
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\g\.ivy2\local\io.vertx\vertx-lang-scala3\4.4.6\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/io/vertx/vertx-lang-scala3/4.4.6/vertx-lang-scala3-4.4.6.pom

### Extra

* Anything that can be relevant such as OS version, JVM version
OS: Windows 11
JVM: 17-tem

**Comment by oliver-brm** [comment]
Thanks for reporting! Should be fixed by #11 .

**Comment by deabreu** [comment]
Hello, just reporting problem is still on going:

```
vertx-scala % sbt reStart                 
copying runtime jar...
[info] welcome to sbt 1.10.1 (Eclipse Adoptium Java 17.0.13)
[info] loading settings for project global-plugins from idea.sbt ...
[info] loading global plugins from /Users/ronaldo/.sbt/1.0/plugins
[info] loading settings for project vertx-scala-build from plugins.sbt ...
[info] loading project definition from /Users/ronaldo/BRVRTec/vertx/vertx-scala/project
[info] compiling 2 Scala sources to /Users/ronaldo/BRVRTec/vertx/vertx-scala/project/target/scala-2.12/sbt-1.0/classes ...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.19. Compiling...
[info]   Compilation completed in 9.857s.
[info] loading settings for project root from build.sbt ...
[info] set current project to vertx-scala (in build file:/Users/ronaldo/BRVRTec/vertx/vertx-scala/)
[info] Updating vertx-scala_3
[info] Resolved vertx-scala_3 dependencies
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading io.vertx:vertx-lang-scala_3:4.5.9-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/ronaldo/.ivy2/localio.vertx/vertx-lang-scala_3/4.5.9-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/io/vertx/vertx-lang-scala_3/4.5.9-SNAPSHOT/vertx-lang-scala_3-4.5.9-SNAPSHOT.pom
[error]   not found: /Users/ronaldo/.m2/repository/io/vertx/vertx-lang-scala_3/4.5.9-SNAPSHOT/vertx-lang-scala_3-4.5.9-SNAPSHOT.pom
[error] Error downloading io.vertx:vertx-web:4.5.9-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/ronaldo/.ivy2/localio.vertx/vertx-web/4.5.9-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/io/vertx/vertx-web/4.5.9-SNAPSHOT/vertx-web-4.5.9-SNAPSHOT.pom
[error]   not found: /Users/ronaldo/.m2/repository/io/vertx/vertx-web/4.5.9-SNAPSHOT/vertx-web-4.5.9-SNAPSHOT.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:346)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$39(CoursierDependencyResolution.scala:315)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:315)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:60)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:142)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:144)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:131)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:220)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:169)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3867)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:840)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading io.vertx:vertx-lang-scala_3:4.5.9-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/ronaldo/.ivy2/localio.vertx/vertx-lang-scala_3/4.5.9-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/io/vertx/vertx-lang-scala_3/4.5.9-SNAPSHOT/vertx-lang-scala_3-4.5.9-SNAPSHOT.pom
[error]   not found: /Users/ronaldo/.m2/repository/io/vertx/vertx-lang-scala_3/4.5.9-SNAPSHOT/vertx-lang-scala_3-4.5.9-SNAPSHOT.pom
[error] Error downloading io.vertx:vertx-web:4.5.9-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/ronaldo/.ivy2/localio.vertx/vertx-web/4.5.9-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/io/vertx/vertx-web/4.5.9-SNAPSHOT/vertx-web-4.5.9-SNAPSHOT.pom
[error]   not found: /Users/ronaldo/.m2/repository/io/vertx/vertx-web/4.5.9-SNAPSHOT/vertx-web-4.5.9-SNAPSHOT.pom
[error] Total time: 2 s, completed 23 de out. de 2024 18:56:24

```

Problem occured in MacOS Ventura JVM 17.0.13-tem

**Comment by oliver-brm** [comment]
I've added an sbt resolver for the Vert.x snapshots repository. This should do the trick.

**Comment by oliver-brm** [comment]
Feedback from Discord shows that the temporary fix worked. Plus, Vert.x for Scala is now available in a stable version from Maven Central, so there is no need to pull it from Snapshots anymore.
